format_version: 3
pipelines:
  GoCDPipeline:
    group: myFirstpipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/htetgit/My-project.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Compile:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build
                - -o
                - main
                - .
                command: go
                run_if: passed
