# pipeline.yaml

pipelines:
  MyDockerPipeline:
    group: docker
    materials:
      git-repo:
        git: https://github.com/htetgit/My-project.git
        branch: master # or specify the branch you want to build
        auto_update: true

    stages:
      - name: Build
        jobs:
          - name: BuildDockerImage
            environment_variables:
              DOCKER_BUILD_PATH: C:\Users\htety\OneDrive\Desktop\Test-Docker\Docker-demo
            tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - |
                      cd $DOCKER_BUILD_PATH
                      docker build -t first-pipeline/teasting101:latest .
