# Define environments
environments:
  - name: development

# Define agents
agents:
  - name: admin
    resources: [docker]
    environment_variables:
      GOCD_AGENT_WORK_DIR: C:\Program Files (x86)\Go Agent
      DOCKER_HOST: tcp://docker:2375
    hostname: 127.0.0.1
    operating_system: Windows 10
    agent_state: Idle
    free_space: "857.36 GB"

# Define pipelines
pipelines:
  - name: GoCDPipeline
    group: my_pipeline_group
    label_template: '${COUNT}'
    materials:
      git:
        url: https://github.com/htetgit/My-project.git
        branch: main
    stages:
      - name: Build
        jobs:
          - name: Compile
            agent: admin
            tasks:
              - exec:
                  command: go build -o main .
                  working_directory: C:\Program Files (x86)\Go Agent\work\GoCDPipeline\Build\Comiple
      - name: Dockerize
        jobs:
          - name: BuildDockerImage
            agent: admin
            tasks:
              - exec:
                  command: docker build -t my-golang-app .
                  working_directory: C:\Program Files (x86)\Go Agent\work\GoCDPipeline\Dockerize\BuildDockerImage
